version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-228-246-214.eu-west-1.compute.amazonaws.com
            database: dffcgusnqht0lq
            user: ijmmpknigsovry
            password: 488cd5cf688c4c250dca40d6a31c65e50e551e2b8213a97f171a54105537ee47
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true